### ISSUE TITLE
Plugin for Ruckig Trajectory Generator

### ISSUE THREAD

**Issue by pantor** [CoppeliaRobotics/simExtRML2#1]
Hi!

As the author of [Ruckig](https://github.com/pantor/ruckig) (a library for online trajectory generation similar to Reflexxes), I've created following [CoppeliaSim plugin](https://github.com/pantor/simExtRuckig) to test and visualize robot motions. I thought that this plugin might be of interest for you.

In general, Ruckig is an open-source alternative to Reflexxes Type IV. It has a very similar API, so my plugin is largely based on this repository. Ruckig has several advantages over Reflexxes Type II: (1) It outputs jerk-constrained motions, (2) it allows for a target acceleration, (3) it allows for different min and max limits and (4) is around twice as fast in calculation.

The plugin itself is tested with the latest CoppeliaSim on Ubuntu 18.04, configured via cmake. I've kept the name of the shared library `libsimExtRML2.so` so the plugin can be used as a drop-in replacement.

**Comment by Coppelia** [comment]
Hello Lars,
thanks a lot for the info and offering a replacement plugin for the RML functionality! Will message you a bit more later...
Cheers
